#!/usr/bin/php
<?php
$moddir = "./factorio/mods";

/*

Script to delete old mod versions from factorio, keeps newest version of every mod.
v1.0

*/



$filer=array();

if ($handle = opendir($moddir)) {
    /* Correctly handling directory entries that may be considered falsy */
    while (false !== ($entry = readdir($handle))) {
        if ($entry === '.' || $entry === '..') {
            continue;
        }
        $filer[]=$entry;
    }
    closedir($handle);
}

sort($filer);

$del = array();
$topmod=array("","0.0.0","");

foreach ($filer as $idx => $fil) {
	$curmod = getver($fil);

	if ($topmod[0] == $curmod[0]) { // Samme mod
		if (version_compare($curmod[1], $topmod[1], '>=')) {
			$del[] = $topmod[2];
			//mprint($topmod, true);
			$topmod = $curmod;
		} else {
			$del[] = $curmod[2];
			//mprint($curmod, true);
		}
	} else { // Ny mod
		//if ($idx>0) $keep[] = $topmod[2];
		//if ($idx>0) mprint($topmod);
		$topmod = $curmod;
	}


}

$res = array_unique($del);
$bytes=0;
foreach ($res as $slett) {
	$f = $moddir . "/" . $slett;
	if (is_dir($f)) {
		mprint($f);
		$bytes+=GetDirectorySize($f);
	} else {
		mprint($f,true);
		$bytes+=filesize($f);
	}
}
if ($bytes == 0){
	mprint("Ingenting å gjøre",true);
	exit(0);
}

mprint(sprintf("%s brukt", human_filesize($bytes)));

$confirm = readline("Delete? [y/N]");
if (strtolower($confirm) == "y") {
	foreach ($res as $slett) {
		$f = $moddir . "/" . $slett;
		if (is_dir($f)) {
			re_rmdir($f);
		} else {
			unlink($f);
		}
	}
	mprint(sprintf("%s diskplass frigjort", human_filesize($bytes)));
} else {
	mprint("Ingenting å gjøre",true);
}


function mprint($mod, $red = false) {
	global $moddir;
	if (is_dir($moddir . "/" . $mod[2])) {
		$msg = sprintf("%s [%s]", $mod[0], $mod[1]);
	} else {
		if (is_array($mod)) {
			$msg=$mod[2];
		} else {
			$msg = $mod;
		}
	}
	if ($red) {
		echo "\033[1;31m".$msg."\033[0m\n";
	} else {
		echo $msg."\n";
	}
}

function getver($mod) {
	global $moddir;
	$pos = strrpos($mod, "_");
	if ($pos > 1) {
		$version = substr($mod, $pos + 1, -4);
		$modname = substr($mod, 0, $pos);
	} else {
		if (is_dir($moddir . "/" . $mod)) {
			$info = json_decode(file_get_contents(sprintf("%s/%s/info.json", $moddir, $mod)), true);
			$version = $info["version"];
		} else {
			$version = "0.0.0";
		}
		$modname = $mod;
	}
	return array($modname, $version, $mod);
}


function human_filesize($bytes, $decimals = 2) {
    $factor = floor((strlen($bytes) - 1) / 3);
    if ($factor > 0) $sz = 'KMGT';
    return sprintf("%.{$decimals}f", $bytes / pow(1024, $factor)) . @$sz[$factor - 1] . 'B';
}

function GetDirectorySize($path){
    $bytestotal = 0;
    $path = realpath($path);
    if($path!==false && $path!='' && file_exists($path)){
        foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS)) as $object){
            $bytestotal += $object->getSize();
        }
    }
    return $bytestotal;
}


function re_rmdir($dir) {
    $it = new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS);
    $it = new RecursiveIteratorIterator($it, RecursiveIteratorIterator::CHILD_FIRST);
    foreach($it as $file) {
        if ($file->isDir()) rmdir($file->getPathname());
        else unlink($file->getPathname());
    }
    rmdir($dir);
}

?>
